db:
        image: postgres:latest
        restart: always
        volumes:
           - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
           - /etc/localtime:/etc/localtime:ro
lup1:
        build: lup1
        restart: always
        links:
                - db:db
        ports:
                - "127.0.0.1:8080:8080"
